% --------------------------------------
% -------------------------------------------------
% APARTADO A2 - Matrices de transformación homogénea
% -------------------------------------------------

function [TB0,T01,T12,T23,T34,T45,T56] = matricesTH
% Definición de variables simbólicas (no cambiar)
syms L0 L1 L1A L1B L2 L2A L2B L3 L3A L3B L4 L4A L4B L5 L5A L5B L6 L6A L6B real  
syms q1 q2 q3 q4 q5 q6 real  
PI = sym(pi);

% - Sustituya los valores de las siguiente matrices por los que corresponda.
% - Emplee expresiones simbólicas L0, L1, L2A, etc para las longitudes, 
%   valores en radianes para los ángulos (por ejemplo PI/2), así como
%   las funciones sin y cos para las correspondientes funciones
%   trigonométricas.
% - Use la variable PI (en mayúsculas) para referirse a pi radianes
% - Las matrices deben incluir los offsets correspondientes en la variables
%   articulares, q1, q2, q3.
 
% Matriz de transformación de sistema Base a 0
TB0 = [ 1,       0,    0,    0           ;...
        0,       1,    0,    0           ;...
        0,       0,    1,    L0           ;...
        0,       0,    0,    1           ]; 
% Matriz de transformación de sistema 0 a 1
T01 = [ cos(q1), 0,  sin(q1), 0          ;...
        sin(q1), 0, -cos(q1), 0          ;...
        0,       1,     0,    0          ;...
        0,       0,     0,    1          ];  
% Matriz de transformación de sistema 1 a 2
T12 = [ cos(q2 - PI/2),  0, -sin(q2 - PI/2), -L2B*cos(q2 - PI/2) ;...
        sin(q2 - PI/2),  0,  cos(q2 - PI/2), -L2B*sin(q2 - PI/2) ;...
                     0, -1,               0,                 -L1 ;...
                     0,  0,               0,                   1 ];  
% Matriz de transformación de sistema 2 a 3
T23 = [ 1, 0, 0,             0           ;...
        0, 1, 0,             0           ;...
        0, 0, 1, L3 + L2A + q3           ;...
        0, 0, 0,             1           ];  
% Matriz de transformación de sistema 3 a 4
T34 = [ cos(q4 + PI/2), 0,  sin(q4 + PI/2),  0 ;...
        sin(q4 + PI/2), 0, -cos(q4 + PI/2),  0 ;...
                     0, 1,               0, L4 ;...
                     0, 0,               0,  1];  
% Matriz de transformación de sistema 4 a 5
T45 = [ 0, -1,  0,       0  ;...
        -1,  0,  0,       0 ;...
        0,  0, -1, L5 + q5  ;...
        0,  0,  0,       1 ];  
% Matriz de transformación de sistema 5 a 6
T56 = [ cos(q6 + PI/2), -sin(q6 + PI/2), 0, L6*cos(q6 + PI/2) ;...
        sin(q6 + PI/2),  cos(q6 + PI/2), 0, L6*sin(q6 + PI/2) ;...
                    0,               0, 1,                 0  ;...
                     0,               0, 0,                 1 ];  

end